#######
##
##
#######
##
##
##
##

#######
##
##
#######
##
##
#######

##     ##
###   ###
#### ####
## ### ##
##     ##
##     ##
##     ##


############
    ##
    ##
    ##
    ##
    ##
############

########
  ##
  ##
  ##
  ##
  ##
  ##


#######
##
##
#######
##
##
#######







# This is the config for the plugin FemiteBox

#Name for the itemtag show-item
show-item-tag="show-item"