name: FemiteBox
version: '0.1'
main: smitegee.femiteboxplugin.FMB
api-version: '1.19'

commands:

    femiteboxplugin:
        description: idk
        permission: femiteboxplugin.commands.femiteboxplugin
        permission-message: Sorry! Isnt available right now
        aliases: [fbp, fmbp, fmbp2, fmb, ]

    fmbsee:
        description: idk
        permission: femiteboxplugin.commands.fmbinvsee
        permission-message: nope
        aliases: [fmbs, fmsee, fsee,seefmb]



    showtitle:
                description: Shows a title to a player
                usage: /showtitle <player> <title> <subtitle>
                permission: femiteboxplugin.admin.commands.showtitle

    maxhp:
                description:
                aliases: [setmaxhp, maxhp, setmaximumhp, setmaximumhealth, ineedtosetmyhealth, ineedtosetmymaximumhealthto]
                permission-message: you are trash mister
                permission: femiteboxplugin.admin.commands.maxhp

    nv_class:
                  description: Gives Night Vision
                  permission: femiteboxplugin.default
                  permission-message: how
                  aliases: [ night_vision, night, vision, nightvision, nv, nightv, nvision]
