name: FemiteBox
version: '1.10'
main: smitegee.femiteboxplugin.FMB
api-version: '1.19'

commands:
    femiteboxplugin:
        description: Powerful enough to get someone an item
        permission: femiteboxplugin.commands.femiteboxplugin
        permission-message: Sorry! Isnt available right now
        aliases: [fbp, fmbp, fmbp2]

    fmbadmin:
        description: Powerful enough to get someone an item
        permission: femiteboxplugin.commands.fmbadmin
        permission-message: Sorry! Isnt available right now
        aliases: [fmb, fmba]

    fmbsee:
        description: Powerful enough to get someone an item
        permission: femiteboxplugin.commands.fmbinvsee
        permission-message: nope
        aliases: [fmbs, fmsee, fsee,seefmb]