name: FBP
version: '1.6.3'
main: smitegee.femiteboxplugin.FMB
api-version: '1.19'

commands:
    femiteboxplugin:
      description: Powerful enough to get someone an item
      permission: femiteboxplugin.commands.femiteboxplugin
      permission-message: Sorry! Isnt available right now
      aliases: [fbp, fmb, fmbp, fmbp]