name: FemiteBox
version: '1.10.3'
main: smitegee.femiteboxplugin.FMB
api-version: '1.19'

commands:
    femiteboxplugin:
        description: Powerful enough to get someone an item
        permission: femiteboxplugin.commands.femiteboxplugin
        permission-message: Sorry! Isnt available right now
        aliases: [fbp, fmbp, fmbp2, fmb, ]

    fmbsee:
        description: Powerful enough to get someone an item
        permission: femiteboxplugin.commands.fmbinvsee
        permission-message: nope
        aliases: [fmbs, fmsee, fsee,seefmb]
    summonmob:
            description: Powerful enough to get someone an item
            permission: femiteboxplugin.commands.default
            permission-message: nope
    keypad:
                description: Powerful enough to get someone an item
                permission: femiteboxplugin.commands.default
                permission-message: nope
    crafting:
                description: Powerful enough to get someone an item
                permission: femiteboxplugin.commands.default
                permission-message: nope